name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            rm -rf pixelArt
            git clone ${{ secrets.GIT_PROJECT }}
            cd pixelArt
            rm -rf .github .git example
            rm LICENSE README.md
            echo 'Deployment successful'
